### ISSUE TITLE
关于项目分工与合作

### ISSUE THREAD

**Issue by DiamonWoo** [xloger/LawRefBookAndroid#1]
Github上类似项目有好几个，是否可以考虑分工合作？
看看我的项目，欢迎发表意见：
#https://github.com/DiamonWoo/Laosheng.top/issues/1#issue-1192924216

**Comment by xloger** [comment]
之前忙不好意思没及时回复。
我做这个的初衷是因为它纯粹，如 RanKKI 所说的简单方便，看什么查什么一目了然。即：它是且仅是一个离线的法律法规的阅读和查询 App。
您的项目我了解了一下，我对法律本身是不太了解的，导致看的过程比较懵，法律法规收集完善方面也是 RanKKI 在负责。我个人觉得这个项目我还是侧重于法律法规本身的浏览体验改善和搜索，其他方向我没啥想法。
