### ISSUE TITLE
还在更新吗

### ISSUE THREAD

**Issue by Familyye** [xloger/LawRefBookAndroid#2]
这个还在维护吗大佬

**Comment by xloger** [comment]
你好，这个项目我觉得很有意义，能帮助到他人门槛更低地了解查询法律，是会尽量维护下去的。
但是前段时间因为换工作和适应新公司比较忙，所以精力没在这上面。

这两周我尽量抽时间再更新下法律库，加点功能，完善体验

**Comment by xloger** [comment]
这周末抽了点时间去更新了一下最新规则和做到了更好的适配，优化了搜索体验。

V1.1.0 已经在 Github releases 和 Google Play 上更新啦~
